import { AbsoluteFill } from 'remotion';
import type { DemoId } from './florvia-demo';
import './app-mockups.css';

const labels: Record<DemoId, string> = { receive: 'Recepción', inventory: 'Inventario', dispatch: 'Despacho', liquidation: 'Liquidaciones', dashboard: 'Resumen' };
const receipts = [['REC-041', 'José Bolaños', 'Freedom', '600', 'Clasificada'], ['REC-042', 'Marco Quimbiamba', 'Mondial', '400', 'Por clasificar'], ['REC-043', 'José de la Salle', 'Explorer', '200', 'Clasificada']];

function Table({ headers, rows }: { headers: string[]; rows: string[][] }) {
  return <table><thead><tr>{headers.map(h => <th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r, i) => <tr key={i}>{r.map((v, j) => <td key={j}>{j === r.length - 1 ? <span className="status">{v}</span> : v}</td>)}</tr>)}</tbody></table>;
}

function Stats({ items }: { items: [string, string, string][] }) {
  return <div className="stats">{items.map(([label, value, note], i) => <div className={i === 0 ? 'primary-stat' : ''} key={label}><span>{label}</span><strong>{value}</strong><small>{note}</small></div>)}</div>;
}

export function AppMockup({ demo }: { demo: DemoId }) {
  return <AbsoluteFill className="app-preview"><aside className="app-nav"><div className="app-logo"><span className="florvia-leaves" aria-hidden="true"><i/><i/><i/></span> Florvia</div><div className="workspace">Postcosecha<small>Espacio de trabajo</small></div><small className="nav-caption">OPERACIÓN</small>{(['dashboard', 'receive', 'inventory', 'dispatch', 'liquidation'] as DemoId[]).map((id, i) => <div className={`nav-item ${id === demo ? 'selected' : ''}`} key={id}><span className="nav-icon">{['▦', '↓', '▤', '↑', '≡'][i]}</span>{labels[id]}</div>)}<div className="nav-bottom"><span className="workspace-avatar">F</span><div>Equipo Florvia</div></div></aside><main className="app-work"><header><div><small>Postcosecha / {labels[demo]}</small><h1>{demo === 'dashboard' ? 'Tu operación, hoy' : labels[demo]}</h1></div><span className="search">Buscar en Florvia</span></header><div className="preview-disclosure" aria-hidden="true" />
    {demo === 'receive' && <><section className="panel"><div className="panel-heading"><h2>Ingresos de flor</h2><span className="action">+ Nueva recepción</span></div><Stats items={ [['Tallos recibidos', '1.200', '3 recepciones'], ['Clasificados', '800', '2 registros'], ['Por clasificar', '400', '1 registro']] }/><div className="tabs"><b>Todos los ingresos</b><span>Por clasificar</span></div><Table headers={['Ingreso', 'Origen', 'Variedad', 'Tallos', 'Estado']} rows={receipts}/></section><section className="panel lower-panel"><h2>Última recepción</h2><div className="detail-line"><strong>REC-043 · Explorer</strong><span>José de la Salle</span><b>200 tallos</b></div><p>Clasificación completa. Disponible para inventario.</p></section></>}
    {demo === 'inventory' && <><section className="panel"><div className="panel-heading"><h2>Disponibilidad</h2><span className="filter">Todas las variedades ▾</span></div><Stats items={ [['En inventario', '800', 'Tallos clasificados'], ['Comprometidos', '300', 'Asignados a pedidos'], ['Disponibles', '500', 'Sin asignación']] }/><Table headers={['Variedad', 'Longitud', 'Existencia', 'Comprometido', 'Disponible']} rows={ [['Freedom', '60 cm', '600', '200', '400'], ['Explorer', '60 cm', '200', '100', '100']] }/></section><section className="panel lower-panel"><div className="panel-heading"><h2>Movimientos · Freedom</h2><span className="status">Lote REC-041</span></div><div className="movement"><span>Ingreso clasificado</span><b>+600 tallos</b></div><div className="movement"><span>Asignación a pedido PED-018</span><b>200 comprometidos</b></div></section></>}
    {demo === 'dispatch' && <><section className="panel"><div className="panel-heading"><h2>Pedidos por preparar</h2><span className="action">+ Nuevo pedido</span></div><Table headers={['Pedido', 'Cliente', 'Tallos', 'Estado']} rows={ [['PED-018', 'Cliente de mostrador', '300', 'En preparación']] }/></section><div className="split-panels"><section className="panel"><h2>Preparación de cajas</h2><p>PED-018 · Cliente de mostrador</p><div className="packing"><span>CAJA 01</span><strong>Freedom</strong><b>200 tallos · 60 cm</b></div><div className="packing"><span>CAJA 02</span><strong>Explorer</strong><b>100 tallos · 60 cm</b></div></section><section className="panel dark-panel"><h2>Antes de despachar</h2><p>Revisa el contenido del pedido.</p><div className="check-row">✓ Cliente identificado</div><div className="check-row">✓ 300 tallos asignados</div><div className="check-row">✓ 2 cajas preparadas</div><span className="action green-action">Marcar como preparado</span></section></div></>}
    {demo === 'liquidation' && <><section className="panel"><div className="panel-heading"><h2>José Bolaños</h2><span className="status">Borrador</span></div><p>Recepción REC-041 · Freedom · 600 tallos</p><Table headers={['Concepto', 'Cantidad', 'Precio unitario', 'Importe']} rows={ [['Tallos clasificados', '600', '$0,20', '$120,00']] }/><div className="totals"><div><span>Total</span><b>$120,00</b></div><div><span>Pagos registrados</span><b>$0,00</b></div><div className="balance"><span>Saldo del borrador</span><strong>$120,00</strong></div></div><div className="panel-heading"><p>Pendiente de revisión.</p><span className="action">Guardar borrador</span></div></section><section className="panel lower-panel"><h2>Documentos del proveedor</h2><div className="detail-line"><span>Factura del proveedor</span><span className="status">Pendiente</span></div></section></>}
    {demo === 'dashboard' && <><section className="panel"><div className="panel-heading"><h2>Resumen de operación</h2><div className="tabs compact"><b>Hoy</b><span>Semana</span></div></div><Stats items={ [['Flor recibida', '1.200', 'Tallos ingresados'], ['Disponibles', '500', 'Tallos sin asignación'], ['Por preparar', '1', 'Pedido · 300 tallos']] }/><div className="pipeline"><div className="panel-heading"><h3>Clasificación de recepción</h3><strong>800 de 1.200 tallos</strong></div><div className="progress"><span/></div><div className="detail-line"><span>800 clasificados</span><span>400 por clasificar</span></div></div></section><div className="split-panels"><section className="panel"><h2>Requiere seguimiento</h2><Table headers={['Registro', 'Pendiente']} rows={ [['REC-042', 'Clasificación'], ['PED-018', 'Preparación']] }/></section><section className="panel dark-panel"><h2>Proveedores</h2><p>Saldo del borrador de liquidación</p><strong className="large-balance">$120,00</strong><span>José Bolaños</span><span className="action green-action">Revisar liquidación</span></section></div></>}
  </main></AbsoluteFill>;
}
